config/routes.rb
Rails.application.routes.draw do
  get 'movies/index'
  get 'movies/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, except: %i[edit update] do
    resources :bookmarks, only: %i[new create]
    resources :movies, only: :create
  end
  resources :bookmarks, only: :destroy
  resources :movies, only: %i[index destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: 'This movie is already in the list.' }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :thumbnail

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[destroy]
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'bookmarks/new'
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
    @bookmark = Bookmark.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @list.destroy
    redirect_to root_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :thumbnail)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    if params[:query].present?
      @query = params[:query]
      @movies = Movie.where('title ILIKE ?', "%#{params[:query]}%")
    else
      @movies = Movie.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form-bookmark.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie, collection: Movie.all.order(:title), prompt: 'Select a movie', input_html: { class: 'select2' } %>
  <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
  <div class="d-flex justify-content-between">
    <%= link_to "Cancel", list_path(@list), class: 'btn btn-outline-danger my-2 my-sm-0' %>
    <%= f.submit 'Add movie', class: 'btn btn-outline-primary my-2 my-sm-0' %>
  </div>
<% end %>

app/views/bookmarks/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form new-bookmark-form">
        <h1>Add a movie to: <br><span><%= @list.name %></span></h1>
        <div class="mt-3">
          <%= render "form-bookmark", list: @list %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <main>
      <%= yield %>
    </main>
    <%= render partial: 'shared/footer' %>
  </body>
</html>

app/views/lists/_form-list.html.erb
<%= simple_form_for list do |f| %>
  <%= f.input :name %>
    <div class="choose_file">
      <span>Choose file for Thumbnail</span>
      <%= f.input :thumbnail, as: :file, label: false%>
    </div>
  <div class="d-flex justify-content-between">
    <%= link_to 'Cancel', lists_path, class: 'btn btn-outline-danger my-2 my-sm-0' %>
    <%= f.submit class: 'btn btn-outline-primary my-2 my-sm-0' %>
  </div>
<% end %>

app/views/lists/index.html.erb
<div class="neon-wrapper">
  <h2>Watchlists</h2>
</div>
<div class="container">
  <div class="row">
    <% @lists.each do |list| %>
        <%= link_to list_path(list), class:'text-decoration-none' do %>
        <% if list.thumbnail.attached? %>
          <div class="card-list" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('<%= cl_image_path list.thumbnail.key%>')">
            <%= list.name %>
          </div>
        <% else %>
          <div class="card-list" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('<%= asset_path 'default-thumbnail.jpg'%>')">
            <%= list.name %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form new-list-form">
        <h1>Add a new List</h1>
        <div class="mt-3">
          <%= render "form-list", list: @list %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="custom-container">
  <div class="list-name">
    <div class="d-flex">
      <h1><%= @list.name %></h1>
      <div class="movies-count">
        <span class="movie-tag">( <%= pluralize(@list.movies.size, 'movie') %> )</span>
      </div>
    </div>
    <%= link_to new_list_bookmark_path(@list) do %>
      <i class="fas fa-plus-circle"></i>
    <% end %>
  </div>
  <div>
    <small><em class="text-muted"><%= "You haven't saved any movies yet!" if @list.movies.empty? %></em></small>
  </div>
  <div class="movies-wrapper">
    <div class="left-column">
      <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
        <div class="card-movie" data-card-movie="<%= movie.to_json %>">
          <%= image_tag movie.poster_url, alt: movie.title%>
          <div class="movie-info">
            <div class="info-main">
              <span class="movie-title"><%= movie.title %></span> <span class="movie-rating">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span>
              <small class="text-right flex-shrink-0"><%= link_to bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-primary' do %></small>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </div>
            <p>
              <small class="text-muted"><%= movie.overview %></small>
            </p>
          </div>
        </div>
        <% end %>
    </div>
    <div class="right-column">
      <div class="movie-details-wrapper">
        <div class="movie-text">
          <img id="movie-poster" src="" alt="movie-title">
          <h3 id="movie-title"></h3>
          <h4 id="movie-original-title"></h4>
          <p id="movie-overview"></p>
        </div>
        <div class="d-flex justify-content-between movie-text-bottom">
          <p id="movie-rating"></p>
          <p id="movie-release-date"></p>
          <p id="movie-original-language"></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<div class="row m-3">
  <div class="col">
    <div class="my-5 searched-movies">
      <% if @query %>
        <h1>You searched for "<span><strong><%= @query %></strong></span>"<br>We found <span><strong> <%= @movies.count == 1 ? "1 movie" : "#{@movies.count} movies" %></strong></span> out of <%= Movie.count %> from our database.</h1>
        <div class="movies-wrapper">
          <div class="left-column">
            <% @movies.each do |movie| %>
              <div class="card-movie" data-card-movie="<%= movie.to_json %>">
                <%= image_tag movie.poster_url, alt: movie.title%>
                <div class="movie-info">
                  <div class="info-main">
                    <span class="movie-title"><%= movie.title %></span> <span class="movie-rating">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span>
                  </div>
                  <p>
                    <small class="text-muted"><%= movie.overview %></small>
                  </p>
                </div>
              </div>
              <% end %>
          </div>
          <div class="right-column">
            <div class="movie-details-wrapper">
              <div class="movie-text">
                <img id="movie-poster" src="" alt="movie-title">
                <h3 id="movie-title"></h3>
                <h4 id="movie-original-title"></h4>
                <p id="movie-overview"></p>
              </div>
              <div class="d-flex justify-content-between movie-text-bottom">
                <p id="movie-rating"></p>
                <p id="movie-release-date"></p>
                <p id="movie-original-language"></p>
              </div>
            </div>
        </div>
      <% else %>
        <h1>All <%= Movie.count %> movies</h1>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="navbar-light">
  <div class="container footer-content">
    <p>Created by <span>piotr</span></p>
    <div class="social-links">
      <div class="social-link">
        <a href="#"><i class="fab fa-facebook" id="facebook"></i></a>
      </div>
      <div class="social-link">
        <a href="#"><i class="fab fa-linkedin" id="linkedin"></i></a>
      </div>
      <div class="social-link">
        <a href="#"><i class="fab fa-github" id="github"></i></a>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light d-flex">
  <div class="d-flex" id="navbar-right">
    <i class="fas fa-film"></i>
    <%= link_to 'Watchlist', root_path, class: 'navbar-brand' %>
  </div>
  <div class="d-flex">
    <div>
      <%= form_tag movies_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          placeholder: "Find a movie", class: "p-2 pr-5"%>
        <%= submit_tag "Search", class: "btn-red-opposite" %>
      <% end %>
    </div>
    <% if defined?(@list) && @list[:id] %>
      <div class="d-flex">
        <%= link_to 'Delete List', list_path(@list), method: :delete, class: 'btn btn-outline-danger my-2 my-sm-0 ml-2', data: { confirm: 'Are you sure you want to delete this list?' } %>
        <%= link_to 'Add List', new_list_path, class: 'btn btn-outline-primary my-2 my-sm-0 ml-2'%>
      </div>
    <% else %>
      <div>
        <%= link_to 'Add List', new_list_path, class: 'btn btn-outline-primary my-2 my-sm-0 ml-2'%>
      </div>
    <% end %>
  </div>
</nav>